export default {
  'Append end event': '追加结束事件',
  'Append gateway': '追加网关',
  'Append task': '追加任务',
  'Append intermediate/boundary event': '追加中间抛出事件/边界事件',
  'Activate global connect tool': '激活全局连接工具',
  'Append {type}': '添加 {type}',
  'Add Lane above': '在上面添加道',
  'Divide into two Lanes': '分割成两个道',
  'Divide into three Lanes': '分割成三个道',
  'Add Lane below': '在下面添加道',
  'Append compensation activity': '追加补偿活动',
  'Connect to other element': '连接到其他元素',
  'Change type': '修改类型',
  'Create element': '创建元素',
  'Change element': '更改元素',
  'Connect using Association': '使用关联连接',
  'Connect using Sequence/MessageFlow or Association': '使用顺序/消息流或者关联连接',
  'Connect using DataInputAssociation': '使用数据输入关联连接',
  'Delete': '移除',
  'Activate hand tool': '激活抓手工具',
  'Activate lasso tool': '激活套索工具',
  'Activate create/remove space tool': '激活创建/删除空间工具',
  'Create expanded sub-process': '创建扩展子过程',
  'Create intermediateThrowEvent/boundaryEvent': '创建中间抛出事件/边界事件',
  'Participants': '参与者',
  'Create pool/participant': '创建池/参与者',
  'Expanded pool/participant': '展开的空创建池/参与者',
  'Empty pool/participant': '空的创建池/参与者',
  'Parallel Multi Instance': '并行多重事件',
  'Sequential Multi Instance': '时序多重事件',
  'Data': '数据',
  'Data Object Reference': '数据对象参考',
  'Data Store Reference': '数据存储参考',
  'Loop': '循环',
  'Ad-hoc': '即席',
  'Create {type}': '创建 {type}',
  'Create start event': '创建开始事件',
  'Create end event': '创建结束事件',
  'Create task': '创建任务',
  'Create user task': '创建用户任务',
  'Create gateway': '创建网关',
  'Create data object reference': '创建数据对象',
  'Create data store reference': '创建数据存储',
  'Create group': '创建分组',
  'Create intermediate/boundary event': '创建中间/边界事件',
  'Message Start Event': '消息开始事件',
  'Timer Start Event': '定时开始事件',
  'Conditional Start Event': '条件开始事件',
  'Signal Start Event': '信号开始事件',
  'Error Start Event': '错误开始事件',
  'Escalation Start Event': '升级开始事件',
  'Compensation Start Event': '补偿开始事件',
  'Message Start Event (non-interrupting)': '消息开始事件（非中断）',
  'Timer Start Event (non-interrupting)': '定时开始事件（非中断）',
  'Conditional Start Event (non-interrupting)': '条件开始事件（非中断）',
  'Signal Start Event (non-interrupting)': '信号开始事件（非中断）',
  'Escalation Start Event (non-interrupting)': '升级开始事件（非中断）',
  'Message Intermediate Catch Event': '消息中间捕获事件',
  'Message Intermediate Throw Event': '消息中间抛出事件',
  'Timer Intermediate Catch Event': '定时中间捕获事件',
  'Escalation Intermediate Throw Event': '升级中间抛出事件',
  'Conditional Intermediate Catch Event': '条件中间捕获事件',
  'Link Intermediate Catch Event': '链接中间捕获事件',
  'Link Intermediate Throw Event': '链接中间抛出事件',
  'Compensation Intermediate Throw Event': '补偿中间抛出事件',
  'Signal Intermediate Catch Event': '信号中间捕获事件',
  'Signal Intermediate Throw Event': '信号中间抛出事件',
  'Collapsed Pool': '折叠池',
  'Expanded Pool': '展开池',
  'no parent for {element} in {parent}': '在{parent}里，{element}没有父类',
  'no shape type specified': '没有指定的形状类型',
  'flow elements must be children of pools/participants': '流元素必须是池/参与者的子类',
  'out of bounds release': 'out of bounds release',
  'more than {count} child lanes': '子道大于{count} ',
  'element required': '元素不能为空',
  'diagram not part of bpmn:Definitions': '流程图不符合bpmn规范',
  'no diagram to display': '没有可展示的流程图',
  'no process or collaboration to display': '没有可展示的流程/协作',
  'element {element} referenced by {referenced}#{property} not yet drawn':
    '由{referenced}#{property}引用的{element}元素仍未绘制',
  'already rendered {element}': '{element} 已被渲染',
  'failed to import {element}': '导入{element}失败',
  'Append element': '添加节点',
  'Add text annotation': '添加备注',

  'Set color': '设置节点颜色',
  'Default': '默认',
  'Blue': '蓝',
  'Orange': '橙',
  'Green': '绿',
  'Red': '红',
  'Purple': '紫',

  'Parallel multi-instance': '并行多实例',
  'Sequential multi-instance': '串行多实例',

  'Empty pool/participant (removes content)': '清空泳道（删除内容）',
  'Participant multiplicity': '参与者多重性',
}
