export default {
    'Append end event': '追加结束事件',
    'Append gateway': '追加网关',
    'Append task': '追加任务',
    'Append user task': '追加活动节点',
    'Activate global connect tool': '激活全局连接工具',
    'Append {type}': '添加 {type}',
    'Connect to other element': '连接到其他元素',
    'Change type': '修改类型',
    'Create element': '创建元素',
    'Change element': '更改元素',
    'Connect using Association': '使用关联连接',
    'Delete': '移除',
    'Activate hand tool': '激活抓手工具',
    'Activate lasso tool': '激活套索工具',
    'Activate create/remove space tool': '激活创建/删除空间工具',
    'Create {type}': '创建 {type}',
    'Create start event': '创建开始事件',
    'Create end event': '创建结束事件',
    'Create user task': '创建活动节点',
    'Create gateway': '创建网关',
    'no parent for {element} in {parent}': '在{parent}里，{element}没有父类',
    'no shape type specified': '没有指定的形状类型',
    'element required': '元素不能为空',
    'Append element': '添加节点',
    'Add text annotation': '添加备注',

    'Set color': '设置节点颜色',
    'Default': '默认',
    'Blue': '蓝',
    'Orange': '橙',
    'Green': '绿',
    'Red': '红',
    'Purple': '紫',

    'Align elements': '对齐元素',
    'Align elements left': '靠左对齐',
    'Align elements center': '垂直居中对齐',
    'Align elements right': '靠右对齐',
    'Align elements top': '靠上对齐',
    'Align elements middle': '水平居中对齐',
    'Align elements bottom': '靠下对齐',

}
