export default {
  'Task': '普通任务',
  'Tasks': '任务',
  'Send task': '发送任务',
  'Receive task': '接收任务',
  'User task': '用户任务',
  'Manual task': '手工任务',
  'Business rule task': '业务规则任务',
  'Service task': '服务任务',
  'Script task': '脚本任务',
  'Call activity': '调用活动',
  'Sub-process': '子流程',
  'Sub-process (collapsed)': '子流程（折叠的）',
  'Sub-process (expanded)': '子流程（展开的）',
  'Start Event': '开始事件',
  'Intermediate Throw Event': '中间事件',
  'End Event': '结束事件',
  'Sub-processes': '子流程',
  'Event Sub-process': '事件子流程',
  'Transaction': '事务子流程',
  'Ad-hoc sub-process (collapsed)': '临时子流程（折叠的）',
  'Ad-hoc sub-process (expanded)': '临时子流程（展开的）',
}
